// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * J​S​O​N​ ​E​d​i​t​o​r
		 */
		jsonEditor: string
		/**
		 * U​U​I​D​ ​G​e​n​e​r​a​t​o​r
		 */
		uuid: string
		/**
		 * S​t​r​i​n​g​ ​C​a​s​e
		 */
		stringCase: string
		/**
		 * C​o​l​o​r​ ​C​o​n​v​e​r​t​e​r
		 */
		color: string
		/**
		 * E​n​c​o​d​e​/​D​e​c​o​d​e
		 */
		encodeDecode: string
		/**
		 * H​a​s​h​ ​G​e​n​e​r​a​t​o​r
		 */
		hash: string
		/**
		 * J​W​T​ ​D​e​c​o​d​e​r
		 */
		jwt: string
		/**
		 * R​e​g​e​x​ ​T​e​s​t​e​r
		 */
		regex: string
		/**
		 * D​i​f​f​ ​C​h​e​c​k​e​r
		 */
		diff: string
		/**
		 * S​Q​L​ ​F​o​r​m​a​t​t​e​r
		 */
		sql: string
		/**
		 * T​i​m​e​s​t​a​m​p
		 */
		timestamp: string
		/**
		 * Y​A​M​L​/​J​S​O​N
		 */
		yamlJson: string
		/**
		 * C​r​o​n​ ​E​x​p​r​e​s​s​i​o​n
		 */
		cron: string
		/**
		 * Q​R​ ​C​o​d​e
		 */
		qrCode: string
		/**
		 * E​d​i​t​o​r
		 */
		editor: string
		/**
		 * G​r​a​p​h
		 */
		graph: string
	}
	header: {
		/**
		 * J​S​O​N​ ​E​d​i​t​o​r
		 */
		title: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copyError: string
		/**
		 * F​o​r​m​a​t
		 */
		format: string
		/**
		 * M​i​n​i​f​y
		 */
		minify: string
		/**
		 * S​a​m​p​l​e​ ​D​a​t​a
		 */
		sample: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
	}
	editor: {
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​J​S​O​N​ ​d​a​t​a​ ​h​e​r​e​.​.​.
		 */
		placeholder: string
		/**
		 * I​n​v​a​l​i​d​ ​J​S​O​N
		 */
		invalidJson: string
		/**
		 * V​a​l​i​d​ ​J​S​O​N
		 */
		validJson: string
		/**
		 * E​n​t​e​r​ ​U​R​L​ ​t​o​ ​f​e​t​c​h​ ​J​S​O​N​.​.​.
		 */
		urlPlaceholder: string
		/**
		 * U​R​L​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		urlRequired: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​d​a​t​a
		 */
		fetchError: string
		/**
		 * G​o
		 */
		go: string
		/**
		 * R​e​q​u​e​s​t​ ​S​e​t​t​i​n​g​s
		 */
		requestSettings: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​H​T​T​P​ ​h​e​a​d​e​r​s​ ​a​n​d​ ​r​e​q​u​e​s​t​ ​b​o​d​y
		 */
		requestSettingsDescription: string
		/**
		 * H​e​a​d​e​r​s
		 */
		headers: string
		/**
		 * H​e​a​d​e​r​ ​k​e​y
		 */
		headerKey: string
		/**
		 * H​e​a​d​e​r​ ​v​a​l​u​e
		 */
		headerValue: string
		/**
		 * A​d​d​ ​H​e​a​d​e​r
		 */
		addHeader: string
		/**
		 * B​o​d​y
		 */
		body: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​b​o​d​y​ ​f​o​r​ ​P​O​S​T​/​P​U​T​/​P​A​T​C​H​ ​r​e​q​u​e​s​t​s​.
		 */
		bodyDescription: string
		/**
		 * E​n​t​e​r​ ​r​e​q​u​e​s​t​ ​b​o​d​y​ ​(​J​S​O​N​,​ ​X​M​L​,​ ​e​t​c​.​)
		 */
		bodyPlaceholder: string
		/**
		 * U​s​e​ ​e​d​i​t​o​r​ ​c​o​n​t​e​n​t​ ​a​s​ ​r​e​q​u​e​s​t​ ​b​o​d​y
		 */
		useEditorContent: string
		/**
		 * S​e​n​d​ ​a​s​ ​r​a​w​ ​t​e​x​t​ ​(​d​o​n​'​t​ ​p​a​r​s​e​ ​a​s​ ​J​S​O​N​)
		 */
		sendAsRawText: string
		/**
		 * C​l​e​a​r​ ​A​l​l
		 */
		clearAll: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​l​e​a​r​ ​a​l​l​ ​s​e​t​t​i​n​g​s​?​ ​T​h​i​s​ ​w​i​l​l​ ​r​e​m​o​v​e​ ​a​l​l​ ​s​a​v​e​d​ ​h​e​a​d​e​r​s​,​ ​b​o​d​y​,​ ​a​n​d​ ​U​R​L​ ​f​r​o​m​ ​s​t​o​r​a​g​e​.
		 */
		clearAllConfirm: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * R​e​g​e​n​e​r​a​t​e
		 */
		regenerate: string
		/**
		 * R​e​g​e​n​e​r​a​t​e​ ​v​a​l​u​e​s​ ​w​h​i​l​e​ ​p​r​e​s​e​r​v​i​n​g​ ​J​S​O​N​ ​s​t​r​u​c​t​u​r​e
		 */
		regenerateTooltip: string
		/**
		 * J​S​O​N​ ​v​a​l​u​e​s​ ​r​e​g​e​n​e​r​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		regenerateSuccess: string
	}
	graph: {
		/**
		 * S​h​o​w​ ​{​c​o​u​n​t​}​ ​m​o​r​e
		 * @param {unknown} count
		 */
		showMore: RequiredParams<'count'>
		/**
		 * S​h​o​w​ ​l​e​s​s
		 */
		showLess: string
		/**
		 * E​x​p​a​n​d
		 */
		expand: string
		/**
		 * C​o​l​l​a​p​s​e
		 */
		collapse: string
		/**
		 * E​x​p​a​n​d​ ​a​l​l
		 */
		expandAll: string
	}
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * 한​국​어
		 */
		ko: string
		/**
		 * 日​本​語
		 */
		ja: string
	}
	footer: {
		/**
		 * R​e​a​d​y
		 */
		ready: string
	}
	tabs: {
		/**
		 * R​e​n​a​m​e
		 */
		rename: string
		/**
		 * D​u​p​l​i​c​a​t​e
		 */
		duplicate: string
		/**
		 * E​x​p​o​r​t​ ​J​S​O​N
		 */
		exportJson: string
		/**
		 * C​l​o​s​e​ ​T​a​b
		 */
		closeTab: string
		/**
		 * I​m​p​o​r​t​ ​J​S​O​N​ ​F​i​l​e
		 */
		importJsonFile: string
		/**
		 * N​e​w​ ​T​a​b
		 */
		newTab: string
		/**
		 * I​m​p​o​r​t
		 */
		'import': string
	}
	encodeDecode: {
		/**
		 * E​n​c​o​d​e​/​D​e​c​o​d​e
		 */
		title: string
		/**
		 * E​n​c​o​d​e​ ​o​r​ ​d​e​c​o​d​e​ ​t​e​x​t​ ​u​s​i​n​g​ ​v​a​r​i​o​u​s​ ​e​n​c​o​d​i​n​g​ ​m​e​t​h​o​d​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * O​u​t​p​u​t
		 */
		output: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​e​n​c​o​d​e​ ​o​r​ ​d​e​c​o​d​e​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * B​a​s​e​6​4
		 */
		base64: string
		/**
		 * B​a​s​e​6​4​ ​E​n​c​o​d​e
		 */
		base64Encode: string
		/**
		 * B​a​s​e​6​4​ ​D​e​c​o​d​e
		 */
		base64Decode: string
		/**
		 * U​R​L
		 */
		url: string
		/**
		 * U​R​L​ ​E​n​c​o​d​e
		 */
		urlEncode: string
		/**
		 * U​R​L​ ​D​e​c​o​d​e
		 */
		urlDecode: string
		/**
		 * E​n​c​o​d​e
		 */
		encode: string
		/**
		 * D​e​c​o​d​e
		 */
		decode: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​d​e​c​o​d​e​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​p​u​t​.
		 */
		decodeError: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​e​n​c​o​d​e​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​p​u​t​.
		 */
		encodeError: string
	}
	hash: {
		/**
		 * H​a​s​h​ ​G​e​n​e​r​a​t​o​r
		 */
		title: string
		/**
		 * G​e​n​e​r​a​t​e​ ​h​a​s​h​ ​v​a​l​u​e​s​ ​u​s​i​n​g​ ​v​a​r​i​o​u​s​ ​a​l​g​o​r​i​t​h​m​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​h​a​s​h​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * M​D​5
		 */
		md5: string
		/**
		 * S​H​A​-​1
		 */
		sha1: string
		/**
		 * S​H​A​-​2​5​6
		 */
		sha256: string
		/**
		 * S​H​A​-​5​1​2
		 */
		sha512: string
		/**
		 * G​e​n​e​r​a​t​e
		 */
		generate: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * R​e​s​u​l​t
		 */
		result: string
		/**
		 * A​l​g​o​r​i​t​h​m
		 */
		algorithm: string
	}
	timestamp: {
		/**
		 * T​i​m​e​s​t​a​m​p​ ​C​o​n​v​e​r​t​e​r
		 */
		title: string
		/**
		 * C​o​n​v​e​r​t​ ​b​e​t​w​e​e​n​ ​t​i​m​e​s​t​a​m​p​ ​a​n​d​ ​d​a​t​e
		 */
		description: string
		/**
		 * T​i​m​e​s​t​a​m​p​ ​t​o​ ​D​a​t​e
		 */
		timestampToDate: string
		/**
		 * D​a​t​e​ ​t​o​ ​T​i​m​e​s​t​a​m​p
		 */
		dateToTimestamp: string
		/**
		 * T​i​m​e​s​t​a​m​p
		 */
		timestamp: string
		/**
		 * E​n​t​e​r​ ​t​i​m​e​s​t​a​m​p​ ​(​e​.​g​.​,​ ​1​2​3​4​5​6​7​8​9​0​)
		 */
		timestampPlaceholder: string
		/**
		 * D​a​t​e
		 */
		date: string
		/**
		 * C​u​r​r​e​n​t​ ​T​i​m​e​s​t​a​m​p
		 */
		currentTimestamp: string
		/**
		 * C​o​n​v​e​r​t
		 */
		convert: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * I​n​v​a​l​i​d​ ​t​i​m​e​s​t​a​m​p
		 */
		invalidTimestamp: string
		/**
		 * I​n​v​a​l​i​d​ ​d​a​t​e
		 */
		invalidDate: string
		/**
		 * M​i​l​l​i​s​e​c​o​n​d​s
		 */
		milliseconds: string
		/**
		 * S​e​c​o​n​d​s
		 */
		seconds: string
		/**
		 * U​n​i​t
		 */
		unit: string
	}
	uuid: {
		/**
		 * U​U​I​D​ ​G​e​n​e​r​a​t​o​r
		 */
		title: string
		/**
		 * G​e​n​e​r​a​t​e​ ​u​n​i​v​e​r​s​a​l​l​y​ ​u​n​i​q​u​e​ ​i​d​e​n​t​i​f​i​e​r​s
		 */
		description: string
		/**
		 * G​e​n​e​r​a​t​e
		 */
		generate: string
		/**
		 * G​e​n​e​r​a​t​e​ ​B​u​l​k
		 */
		generateBulk: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * V​e​r​s​i​o​n
		 */
		version: string
		/**
		 * V​e​r​s​i​o​n​ ​1​ ​(​T​i​m​e​s​t​a​m​p​)
		 */
		v1: string
		/**
		 * V​e​r​s​i​o​n​ ​4​ ​(​R​a​n​d​o​m​)
		 */
		v4: string
		/**
		 * C​o​u​n​t
		 */
		count: string
		/**
		 * U​p​p​e​r​c​a​s​e
		 */
		uppercase: string
		/**
		 * I​n​c​l​u​d​e​ ​H​y​p​h​e​n​s
		 */
		hyphens: string
		/**
		 * R​e​s​u​l​t
		 */
		result: string
	}
	stringCase: {
		/**
		 * S​t​r​i​n​g​ ​C​a​s​e​ ​C​o​n​v​e​r​t​e​r
		 */
		title: string
		/**
		 * C​o​n​v​e​r​t​ ​t​e​x​t​ ​b​e​t​w​e​e​n​ ​d​i​f​f​e​r​e​n​t​ ​n​a​m​i​n​g​ ​c​o​n​v​e​n​t​i​o​n​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​c​o​n​v​e​r​t​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * c​a​m​e​l​C​a​s​e
		 */
		camelCase: string
		/**
		 * P​a​s​c​a​l​C​a​s​e
		 */
		pascalCase: string
		/**
		 * s​n​a​k​e​_​c​a​s​e
		 */
		snakeCase: string
		/**
		 * k​e​b​a​b​-​c​a​s​e
		 */
		kebabCase: string
		/**
		 * S​C​R​E​A​M​I​N​G​_​S​N​A​K​E​_​C​A​S​E
		 */
		screamingSnakeCase: string
		/**
		 * d​o​t​.​c​a​s​e
		 */
		dotCase: string
		/**
		 * p​a​t​h​/​c​a​s​e
		 */
		pathCase: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
	}
	color: {
		/**
		 * C​o​l​o​r​ ​C​o​n​v​e​r​t​e​r
		 */
		title: string
		/**
		 * C​o​n​v​e​r​t​ ​c​o​l​o​r​s​ ​b​e​t​w​e​e​n​ ​d​i​f​f​e​r​e​n​t​ ​f​o​r​m​a​t​s
		 */
		description: string
		/**
		 * H​E​X
		 */
		hex: string
		/**
		 * R​G​B
		 */
		rgb: string
		/**
		 * H​S​L
		 */
		hsl: string
		/**
		 * A​n​d​r​o​i​d​ ​X​M​L
		 */
		android: string
		/**
		 * #​F​F​5​7​3​3
		 */
		hexPlaceholder: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * I​n​v​a​l​i​d​ ​c​o​l​o​r​ ​f​o​r​m​a​t
		 */
		invalidColor: string
	}
	jwt: {
		/**
		 * J​W​T​ ​D​e​c​o​d​e​r
		 */
		title: string
		/**
		 * D​e​c​o​d​e​ ​a​n​d​ ​i​n​s​p​e​c​t​ ​J​S​O​N​ ​W​e​b​ ​T​o​k​e​n​s
		 */
		description: string
		/**
		 * J​W​T​ ​T​o​k​e​n
		 */
		token: string
		/**
		 * P​a​s​t​e​ ​y​o​u​r​ ​J​W​T​ ​t​o​k​e​n​ ​h​e​r​e​.​.​.
		 */
		tokenPlaceholder: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * D​e​c​o​d​e
		 */
		decode: string
		/**
		 * H​e​a​d​e​r
		 */
		header: string
		/**
		 * P​a​y​l​o​a​d
		 */
		payload: string
		/**
		 * S​i​g​n​a​t​u​r​e
		 */
		signature: string
		/**
		 * C​l​a​i​m​s
		 */
		claims: string
		/**
		 * A​l​g​o​r​i​t​h​m
		 */
		algorithm: string
		/**
		 * T​y​p​e
		 */
		type: string
		/**
		 * I​s​s​u​e​r
		 */
		issuer: string
		/**
		 * S​u​b​j​e​c​t
		 */
		subject: string
		/**
		 * A​u​d​i​e​n​c​e
		 */
		audience: string
		/**
		 * E​x​p​i​r​a​t​i​o​n
		 */
		expiration: string
		/**
		 * I​s​s​u​e​d​ ​A​t
		 */
		issuedAt: string
		/**
		 * E​x​p​i​r​e​s​ ​A​t
		 */
		expiresAt: string
		/**
		 * N​o​t​ ​B​e​f​o​r​e
		 */
		notBefore: string
		/**
		 * J​W​T​ ​I​D
		 */
		jwtId: string
		/**
		 * E​x​p​i​r​e​d
		 */
		expired: string
		/**
		 * T​o​k​e​n​ ​N​o​t​ ​Y​e​t​ ​V​a​l​i​d
		 */
		notYetValid: string
		/**
		 * T​o​k​e​n​ ​V​a​l​i​d
		 */
		valid: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * I​n​v​a​l​i​d​ ​J​W​T​ ​t​o​k​e​n
		 */
		invalidToken: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
	}
	regex: {
		/**
		 * R​e​g​e​x​ ​T​e​s​t​e​r
		 */
		title: string
		/**
		 * T​e​s​t​ ​r​e​g​u​l​a​r​ ​e​x​p​r​e​s​s​i​o​n​s​ ​w​i​t​h​ ​r​e​a​l​-​t​i​m​e​ ​m​a​t​c​h​i​n​g
		 */
		description: string
		/**
		 * P​a​t​t​e​r​n
		 */
		pattern: string
		/**
		 * E​n​t​e​r​ ​r​e​g​e​x​ ​p​a​t​t​e​r​n​.​.​.
		 */
		patternPlaceholder: string
		/**
		 * F​l​a​g​s
		 */
		flags: string
		/**
		 * T​e​s​t​ ​S​t​r​i​n​g
		 */
		testString: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​t​e​s​t​.​.​.
		 */
		testStringPlaceholder: string
		/**
		 * M​a​t​c​h​e​s
		 */
		matches: string
		/**
		 * M​a​t​c​h
		 */
		match: string
		/**
		 * G​r​o​u​p​s
		 */
		groups: string
		/**
		 * N​o​ ​m​a​t​c​h​e​s​ ​f​o​u​n​d
		 */
		noMatches: string
		/**
		 * I​n​v​a​l​i​d​ ​r​e​g​u​l​a​r​ ​e​x​p​r​e​s​s​i​o​n
		 */
		invalidRegex: string
		/**
		 * {​c​o​u​n​t​}​ ​m​a​t​c​h​(​e​s​)​ ​f​o​u​n​d
		 * @param {unknown} count
		 */
		matchCount: RequiredParams<'count'>
		/**
		 * H​i​g​h​l​i​g​h​t​e​d​ ​T​e​x​t
		 */
		highlightedText: string
		/**
		 * M​a​t​c​h​ ​D​e​t​a​i​l​s
		 */
		matchDetails: string
		/**
		 * P​o​s​i​t​i​o​n
		 */
		position: string
		/**
		 * C​a​p​t​u​r​e​ ​G​r​o​u​p​s
		 */
		captureGroups: string
		/**
		 * G​l​o​b​a​l​ ​(​g​)
		 */
		global: string
		/**
		 * C​a​s​e​ ​I​n​s​e​n​s​i​t​i​v​e​ ​(​i​)
		 */
		caseInsensitive: string
		/**
		 * M​u​l​t​i​l​i​n​e​ ​(​m​)
		 */
		multiline: string
		/**
		 * D​o​t​ ​A​l​l​ ​(​s​)
		 */
		dotAll: string
		/**
		 * U​n​i​c​o​d​e​ ​(​u​)
		 */
		unicode: string
		/**
		 * S​t​i​c​k​y​ ​(​y​)
		 */
		sticky: string
	}
	diff: {
		/**
		 * D​i​f​f​ ​C​h​e​c​k​e​r
		 */
		title: string
		/**
		 * C​o​m​p​a​r​e​ ​t​w​o​ ​t​e​x​t​s​ ​a​n​d​ ​h​i​g​h​l​i​g​h​t​ ​d​i​f​f​e​r​e​n​c​e​s
		 */
		description: string
		/**
		 * O​r​i​g​i​n​a​l
		 */
		original: string
		/**
		 * M​o​d​i​f​i​e​d
		 */
		modified: string
		/**
		 * E​n​t​e​r​ ​o​r​i​g​i​n​a​l​ ​t​e​x​t​.​.​.
		 */
		originalPlaceholder: string
		/**
		 * E​n​t​e​r​ ​m​o​d​i​f​i​e​d​ ​t​e​x​t​.​.​.
		 */
		modifiedPlaceholder: string
		/**
		 * C​o​m​p​a​r​i​s​o​n​ ​M​o​d​e
		 */
		mode: string
		/**
		 * L​i​n​e​s
		 */
		lines: string
		/**
		 * W​o​r​d​s
		 */
		words: string
		/**
		 * C​h​a​r​a​c​t​e​r​s
		 */
		characters: string
		/**
		 * C​o​m​p​a​r​e
		 */
		compare: string
		/**
		 * S​w​a​p
		 */
		swap: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * S​i​d​e​ ​b​y​ ​S​i​d​e
		 */
		sideBySide: string
		/**
		 * I​n​l​i​n​e
		 */
		inline: string
		/**
		 * N​o​ ​d​i​f​f​e​r​e​n​c​e​s​ ​f​o​u​n​d
		 */
		noDifferences: string
		/**
		 * S​t​a​t​i​s​t​i​c​s
		 */
		statistics: string
		/**
		 * A​d​d​i​t​i​o​n​s
		 */
		additions: string
		/**
		 * D​e​l​e​t​i​o​n​s
		 */
		deletions: string
		/**
		 * C​h​a​n​g​e​s
		 */
		changes: string
		/**
		 * R​e​s​u​l​t
		 */
		result: string
		/**
		 * A​d​d​e​d
		 */
		added: string
		/**
		 * R​e​m​o​v​e​d
		 */
		removed: string
		/**
		 * U​n​c​h​a​n​g​e​d
		 */
		unchanged: string
	}
	yamlJson: {
		/**
		 * Y​A​M​L​ ​↔​ ​J​S​O​N​ ​C​o​n​v​e​r​t​e​r
		 */
		title: string
		/**
		 * C​o​n​v​e​r​t​ ​b​e​t​w​e​e​n​ ​Y​A​M​L​ ​a​n​d​ ​J​S​O​N​ ​f​o​r​m​a​t​s
		 */
		description: string
		/**
		 * Y​A​M​L
		 */
		yaml: string
		/**
		 * J​S​O​N
		 */
		json: string
		/**
		 * Y​A​M​L​ ​t​o​ ​J​S​O​N
		 */
		yamlToJson: string
		/**
		 * J​S​O​N​ ​t​o​ ​Y​A​M​L
		 */
		jsonToYaml: string
		/**
		 * E​n​t​e​r​ ​Y​A​M​L​.​.​.
		 */
		yamlPlaceholder: string
		/**
		 * E​n​t​e​r​ ​J​S​O​N​.​.​.
		 */
		jsonPlaceholder: string
		/**
		 * C​o​n​v​e​r​t
		 */
		convert: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * I​n​v​a​l​i​d​ ​Y​A​M​L​ ​f​o​r​m​a​t
		 */
		invalidYaml: string
		/**
		 * I​n​v​a​l​i​d​ ​J​S​O​N​ ​f​o​r​m​a​t
		 */
		invalidJson: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * I​n​d​e​n​t​ ​S​i​z​e
		 */
		indentSize: string
		/**
		 * S​w​i​t​c​h​ ​D​i​r​e​c​t​i​o​n
		 */
		'switch': string
		/**
		 * Y​A​M​L​ ​I​n​p​u​t
		 */
		yamlInput: string
		/**
		 * J​S​O​N​ ​I​n​p​u​t
		 */
		jsonInput: string
		/**
		 * J​S​O​N​ ​O​u​t​p​u​t
		 */
		jsonOutput: string
		/**
		 * Y​A​M​L​ ​O​u​t​p​u​t
		 */
		yamlOutput: string
		/**
		 * O​u​t​p​u​t​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e​.​.​.
		 */
		outputPlaceholder: string
	}
	sql: {
		/**
		 * S​Q​L​ ​F​o​r​m​a​t​t​e​r
		 */
		title: string
		/**
		 * F​o​r​m​a​t​ ​a​n​d​ ​b​e​a​u​t​i​f​y​ ​S​Q​L​ ​q​u​e​r​i​e​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * O​u​t​p​u​t
		 */
		output: string
		/**
		 * E​n​t​e​r​ ​S​Q​L​ ​q​u​e​r​y​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * F​o​r​m​a​t​t​e​d​ ​S​Q​L​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e​.​.​.
		 */
		outputPlaceholder: string
		/**
		 * F​o​r​m​a​t
		 */
		format: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * U​p​p​e​r​c​a​s​e​ ​K​e​y​w​o​r​d​s
		 */
		uppercase: string
		/**
		 * I​n​d​e​n​t​ ​S​i​z​e
		 */
		indentSize: string
		/**
		 * S​Q​L​ ​D​i​a​l​e​c​t
		 */
		language: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
	}
	cron: {
		/**
		 * C​r​o​n​ ​E​x​p​r​e​s​s​i​o​n​ ​H​e​l​p​e​r
		 */
		title: string
		/**
		 * G​e​n​e​r​a​t​e​ ​a​n​d​ ​e​x​p​l​a​i​n​ ​c​r​o​n​ ​e​x​p​r​e​s​s​i​o​n​s
		 */
		description: string
		/**
		 * C​r​o​n​ ​E​x​p​r​e​s​s​i​o​n
		 */
		expression: string
		/**
		 * e​.​g​.​,​ ​0​ ​0​ ​*​ ​*​ ​*
		 */
		expressionPlaceholder: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		descriptionLabel: string
		/**
		 * N​e​x​t​ ​{​c​o​u​n​t​}​ ​R​u​n​s
		 * @param {unknown} count
		 */
		nextRuns: RequiredParams<'count'>
		/**
		 * M​i​n​u​t​e
		 */
		minute: string
		/**
		 * H​o​u​r
		 */
		hour: string
		/**
		 * D​a​y​ ​o​f​ ​M​o​n​t​h
		 */
		dayOfMonth: string
		/**
		 * M​o​n​t​h
		 */
		month: string
		/**
		 * D​a​y​ ​o​f​ ​W​e​e​k
		 */
		dayOfWeek: string
		/**
		 * G​e​n​e​r​a​t​e
		 */
		generate: string
		/**
		 * E​x​p​l​a​i​n
		 */
		explain: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * I​n​v​a​l​i​d​ ​c​r​o​n​ ​e​x​p​r​e​s​s​i​o​n
		 */
		invalidExpression: string
		/**
		 * E​v​e​r​y​ ​M​i​n​u​t​e
		 */
		everyMinute: string
		/**
		 * E​v​e​r​y​ ​H​o​u​r
		 */
		everyHour: string
		/**
		 * E​v​e​r​y​ ​D​a​y
		 */
		everyDay: string
		/**
		 * E​v​e​r​y​ ​W​e​e​k
		 */
		everyWeek: string
		/**
		 * E​v​e​r​y​ ​M​o​n​t​h
		 */
		everyMonth: string
		/**
		 * B​u​i​l​d​e​r
		 */
		builder: string
		/**
		 * H​e​l​p
		 */
		help: string
		/**
		 * A​n​y​ ​v​a​l​u​e
		 */
		helpAny: string
		/**
		 * E​v​e​r​y​ ​N​ ​u​n​i​t​s
		 */
		helpEvery: string
		/**
		 * R​a​n​g​e​ ​o​f​ ​v​a​l​u​e​s
		 */
		helpRange: string
		/**
		 * L​i​s​t​ ​o​f​ ​v​a​l​u​e​s
		 */
		helpList: string
	}
	qrCode: {
		/**
		 * Q​R​ ​C​o​d​e​ ​G​e​n​e​r​a​t​o​r
		 */
		title: string
		/**
		 * G​e​n​e​r​a​t​e​ ​Q​R​ ​c​o​d​e​s​ ​f​r​o​m​ ​t​e​x​t​ ​o​r​ ​U​R​L​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​o​r​ ​U​R​L​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * T​e​x​t
		 */
		text: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​o​r​ ​U​R​L​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​Q​R​ ​c​o​d​e​.​.​.
		 */
		textPlaceholder: string
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * G​e​n​e​r​a​t​e
		 */
		generate: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * C​o​p​y​ ​L​i​n​k
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * E​r​r​o​r​ ​C​o​r​r​e​c​t​i​o​n
		 */
		errorCorrection: string
		/**
		 * L​o​w
		 */
		low: string
		/**
		 * M​e​d​i​u​m
		 */
		medium: string
		/**
		 * Q​u​a​r​t​i​l​e
		 */
		quartile: string
		/**
		 * H​i​g​h
		 */
		high: string
		/**
		 * L​o​w​ ​(​~​7​%​)
		 */
		errorLevelL: string
		/**
		 * M​e​d​i​u​m​ ​(​~​1​5​%​)
		 */
		errorLevelM: string
		/**
		 * Q​u​a​r​t​i​l​e​ ​(​~​2​5​%​)
		 */
		errorLevelQ: string
		/**
		 * H​i​g​h​ ​(​~​3​0​%​)
		 */
		errorLevelH: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​Q​R​ ​c​o​d​e
		 */
		noQRCode: string
		/**
		 * Q​R​ ​c​o​d​e​ ​d​o​w​n​l​o​a​d​e​d
		 */
		downloadSuccess: string
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * JSON Editor
		 */
		jsonEditor: () => LocalizedString
		/**
		 * UUID Generator
		 */
		uuid: () => LocalizedString
		/**
		 * String Case
		 */
		stringCase: () => LocalizedString
		/**
		 * Color Converter
		 */
		color: () => LocalizedString
		/**
		 * Encode/Decode
		 */
		encodeDecode: () => LocalizedString
		/**
		 * Hash Generator
		 */
		hash: () => LocalizedString
		/**
		 * JWT Decoder
		 */
		jwt: () => LocalizedString
		/**
		 * Regex Tester
		 */
		regex: () => LocalizedString
		/**
		 * Diff Checker
		 */
		diff: () => LocalizedString
		/**
		 * SQL Formatter
		 */
		sql: () => LocalizedString
		/**
		 * Timestamp
		 */
		timestamp: () => LocalizedString
		/**
		 * YAML/JSON
		 */
		yamlJson: () => LocalizedString
		/**
		 * Cron Expression
		 */
		cron: () => LocalizedString
		/**
		 * QR Code
		 */
		qrCode: () => LocalizedString
		/**
		 * Editor
		 */
		editor: () => LocalizedString
		/**
		 * Graph
		 */
		graph: () => LocalizedString
	}
	header: {
		/**
		 * JSON Editor
		 */
		title: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Failed to copy to clipboard
		 */
		copyError: () => LocalizedString
		/**
		 * Format
		 */
		format: () => LocalizedString
		/**
		 * Minify
		 */
		minify: () => LocalizedString
		/**
		 * Sample Data
		 */
		sample: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
	}
	editor: {
		/**
		 * Enter your JSON data here...
		 */
		placeholder: () => LocalizedString
		/**
		 * Invalid JSON
		 */
		invalidJson: () => LocalizedString
		/**
		 * Valid JSON
		 */
		validJson: () => LocalizedString
		/**
		 * Enter URL to fetch JSON...
		 */
		urlPlaceholder: () => LocalizedString
		/**
		 * URL is required
		 */
		urlRequired: () => LocalizedString
		/**
		 * Failed to fetch data
		 */
		fetchError: () => LocalizedString
		/**
		 * Go
		 */
		go: () => LocalizedString
		/**
		 * Request Settings
		 */
		requestSettings: () => LocalizedString
		/**
		 * Configure HTTP headers and request body
		 */
		requestSettingsDescription: () => LocalizedString
		/**
		 * Headers
		 */
		headers: () => LocalizedString
		/**
		 * Header key
		 */
		headerKey: () => LocalizedString
		/**
		 * Header value
		 */
		headerValue: () => LocalizedString
		/**
		 * Add Header
		 */
		addHeader: () => LocalizedString
		/**
		 * Body
		 */
		body: () => LocalizedString
		/**
		 * Configure the request body for POST/PUT/PATCH requests.
		 */
		bodyDescription: () => LocalizedString
		/**
		 * Enter request body (JSON, XML, etc.)
		 */
		bodyPlaceholder: () => LocalizedString
		/**
		 * Use editor content as request body
		 */
		useEditorContent: () => LocalizedString
		/**
		 * Send as raw text (don't parse as JSON)
		 */
		sendAsRawText: () => LocalizedString
		/**
		 * Clear All
		 */
		clearAll: () => LocalizedString
		/**
		 * Are you sure you want to clear all settings? This will remove all saved headers, body, and URL from storage.
		 */
		clearAllConfirm: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Regenerate
		 */
		regenerate: () => LocalizedString
		/**
		 * Regenerate values while preserving JSON structure
		 */
		regenerateTooltip: () => LocalizedString
		/**
		 * JSON values regenerated successfully
		 */
		regenerateSuccess: () => LocalizedString
	}
	graph: {
		/**
		 * Show {count} more
		 */
		showMore: (arg: { count: unknown }) => LocalizedString
		/**
		 * Show less
		 */
		showLess: () => LocalizedString
		/**
		 * Expand
		 */
		expand: () => LocalizedString
		/**
		 * Collapse
		 */
		collapse: () => LocalizedString
		/**
		 * Expand all
		 */
		expandAll: () => LocalizedString
	}
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * 한국어
		 */
		ko: () => LocalizedString
		/**
		 * 日本語
		 */
		ja: () => LocalizedString
	}
	footer: {
		/**
		 * Ready
		 */
		ready: () => LocalizedString
	}
	tabs: {
		/**
		 * Rename
		 */
		rename: () => LocalizedString
		/**
		 * Duplicate
		 */
		duplicate: () => LocalizedString
		/**
		 * Export JSON
		 */
		exportJson: () => LocalizedString
		/**
		 * Close Tab
		 */
		closeTab: () => LocalizedString
		/**
		 * Import JSON File
		 */
		importJsonFile: () => LocalizedString
		/**
		 * New Tab
		 */
		newTab: () => LocalizedString
		/**
		 * Import
		 */
		'import': () => LocalizedString
	}
	encodeDecode: {
		/**
		 * Encode/Decode
		 */
		title: () => LocalizedString
		/**
		 * Encode or decode text using various encoding methods
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Output
		 */
		output: () => LocalizedString
		/**
		 * Enter text to encode or decode...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * Base64
		 */
		base64: () => LocalizedString
		/**
		 * Base64 Encode
		 */
		base64Encode: () => LocalizedString
		/**
		 * Base64 Decode
		 */
		base64Decode: () => LocalizedString
		/**
		 * URL
		 */
		url: () => LocalizedString
		/**
		 * URL Encode
		 */
		urlEncode: () => LocalizedString
		/**
		 * URL Decode
		 */
		urlDecode: () => LocalizedString
		/**
		 * Encode
		 */
		encode: () => LocalizedString
		/**
		 * Decode
		 */
		decode: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Failed to decode. Please check your input.
		 */
		decodeError: () => LocalizedString
		/**
		 * Failed to encode. Please check your input.
		 */
		encodeError: () => LocalizedString
	}
	hash: {
		/**
		 * Hash Generator
		 */
		title: () => LocalizedString
		/**
		 * Generate hash values using various algorithms
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Enter text to generate hash...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * MD5
		 */
		md5: () => LocalizedString
		/**
		 * SHA-1
		 */
		sha1: () => LocalizedString
		/**
		 * SHA-256
		 */
		sha256: () => LocalizedString
		/**
		 * SHA-512
		 */
		sha512: () => LocalizedString
		/**
		 * Generate
		 */
		generate: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Result
		 */
		result: () => LocalizedString
		/**
		 * Algorithm
		 */
		algorithm: () => LocalizedString
	}
	timestamp: {
		/**
		 * Timestamp Converter
		 */
		title: () => LocalizedString
		/**
		 * Convert between timestamp and date
		 */
		description: () => LocalizedString
		/**
		 * Timestamp to Date
		 */
		timestampToDate: () => LocalizedString
		/**
		 * Date to Timestamp
		 */
		dateToTimestamp: () => LocalizedString
		/**
		 * Timestamp
		 */
		timestamp: () => LocalizedString
		/**
		 * Enter timestamp (e.g., 1234567890)
		 */
		timestampPlaceholder: () => LocalizedString
		/**
		 * Date
		 */
		date: () => LocalizedString
		/**
		 * Current Timestamp
		 */
		currentTimestamp: () => LocalizedString
		/**
		 * Convert
		 */
		convert: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Invalid timestamp
		 */
		invalidTimestamp: () => LocalizedString
		/**
		 * Invalid date
		 */
		invalidDate: () => LocalizedString
		/**
		 * Milliseconds
		 */
		milliseconds: () => LocalizedString
		/**
		 * Seconds
		 */
		seconds: () => LocalizedString
		/**
		 * Unit
		 */
		unit: () => LocalizedString
	}
	uuid: {
		/**
		 * UUID Generator
		 */
		title: () => LocalizedString
		/**
		 * Generate universally unique identifiers
		 */
		description: () => LocalizedString
		/**
		 * Generate
		 */
		generate: () => LocalizedString
		/**
		 * Generate Bulk
		 */
		generateBulk: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Version
		 */
		version: () => LocalizedString
		/**
		 * Version 1 (Timestamp)
		 */
		v1: () => LocalizedString
		/**
		 * Version 4 (Random)
		 */
		v4: () => LocalizedString
		/**
		 * Count
		 */
		count: () => LocalizedString
		/**
		 * Uppercase
		 */
		uppercase: () => LocalizedString
		/**
		 * Include Hyphens
		 */
		hyphens: () => LocalizedString
		/**
		 * Result
		 */
		result: () => LocalizedString
	}
	stringCase: {
		/**
		 * String Case Converter
		 */
		title: () => LocalizedString
		/**
		 * Convert text between different naming conventions
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Enter text to convert...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * camelCase
		 */
		camelCase: () => LocalizedString
		/**
		 * PascalCase
		 */
		pascalCase: () => LocalizedString
		/**
		 * snake_case
		 */
		snakeCase: () => LocalizedString
		/**
		 * kebab-case
		 */
		kebabCase: () => LocalizedString
		/**
		 * SCREAMING_SNAKE_CASE
		 */
		screamingSnakeCase: () => LocalizedString
		/**
		 * dot.case
		 */
		dotCase: () => LocalizedString
		/**
		 * path/case
		 */
		pathCase: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
	}
	color: {
		/**
		 * Color Converter
		 */
		title: () => LocalizedString
		/**
		 * Convert colors between different formats
		 */
		description: () => LocalizedString
		/**
		 * HEX
		 */
		hex: () => LocalizedString
		/**
		 * RGB
		 */
		rgb: () => LocalizedString
		/**
		 * HSL
		 */
		hsl: () => LocalizedString
		/**
		 * Android XML
		 */
		android: () => LocalizedString
		/**
		 * #FF5733
		 */
		hexPlaceholder: () => LocalizedString
		/**
		 * Preview
		 */
		preview: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Invalid color format
		 */
		invalidColor: () => LocalizedString
	}
	jwt: {
		/**
		 * JWT Decoder
		 */
		title: () => LocalizedString
		/**
		 * Decode and inspect JSON Web Tokens
		 */
		description: () => LocalizedString
		/**
		 * JWT Token
		 */
		token: () => LocalizedString
		/**
		 * Paste your JWT token here...
		 */
		tokenPlaceholder: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Decode
		 */
		decode: () => LocalizedString
		/**
		 * Header
		 */
		header: () => LocalizedString
		/**
		 * Payload
		 */
		payload: () => LocalizedString
		/**
		 * Signature
		 */
		signature: () => LocalizedString
		/**
		 * Claims
		 */
		claims: () => LocalizedString
		/**
		 * Algorithm
		 */
		algorithm: () => LocalizedString
		/**
		 * Type
		 */
		type: () => LocalizedString
		/**
		 * Issuer
		 */
		issuer: () => LocalizedString
		/**
		 * Subject
		 */
		subject: () => LocalizedString
		/**
		 * Audience
		 */
		audience: () => LocalizedString
		/**
		 * Expiration
		 */
		expiration: () => LocalizedString
		/**
		 * Issued At
		 */
		issuedAt: () => LocalizedString
		/**
		 * Expires At
		 */
		expiresAt: () => LocalizedString
		/**
		 * Not Before
		 */
		notBefore: () => LocalizedString
		/**
		 * JWT ID
		 */
		jwtId: () => LocalizedString
		/**
		 * Expired
		 */
		expired: () => LocalizedString
		/**
		 * Token Not Yet Valid
		 */
		notYetValid: () => LocalizedString
		/**
		 * Token Valid
		 */
		valid: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Invalid JWT token
		 */
		invalidToken: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
	}
	regex: {
		/**
		 * Regex Tester
		 */
		title: () => LocalizedString
		/**
		 * Test regular expressions with real-time matching
		 */
		description: () => LocalizedString
		/**
		 * Pattern
		 */
		pattern: () => LocalizedString
		/**
		 * Enter regex pattern...
		 */
		patternPlaceholder: () => LocalizedString
		/**
		 * Flags
		 */
		flags: () => LocalizedString
		/**
		 * Test String
		 */
		testString: () => LocalizedString
		/**
		 * Enter text to test...
		 */
		testStringPlaceholder: () => LocalizedString
		/**
		 * Matches
		 */
		matches: () => LocalizedString
		/**
		 * Match
		 */
		match: () => LocalizedString
		/**
		 * Groups
		 */
		groups: () => LocalizedString
		/**
		 * No matches found
		 */
		noMatches: () => LocalizedString
		/**
		 * Invalid regular expression
		 */
		invalidRegex: () => LocalizedString
		/**
		 * {count} match(es) found
		 */
		matchCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * Highlighted Text
		 */
		highlightedText: () => LocalizedString
		/**
		 * Match Details
		 */
		matchDetails: () => LocalizedString
		/**
		 * Position
		 */
		position: () => LocalizedString
		/**
		 * Capture Groups
		 */
		captureGroups: () => LocalizedString
		/**
		 * Global (g)
		 */
		global: () => LocalizedString
		/**
		 * Case Insensitive (i)
		 */
		caseInsensitive: () => LocalizedString
		/**
		 * Multiline (m)
		 */
		multiline: () => LocalizedString
		/**
		 * Dot All (s)
		 */
		dotAll: () => LocalizedString
		/**
		 * Unicode (u)
		 */
		unicode: () => LocalizedString
		/**
		 * Sticky (y)
		 */
		sticky: () => LocalizedString
	}
	diff: {
		/**
		 * Diff Checker
		 */
		title: () => LocalizedString
		/**
		 * Compare two texts and highlight differences
		 */
		description: () => LocalizedString
		/**
		 * Original
		 */
		original: () => LocalizedString
		/**
		 * Modified
		 */
		modified: () => LocalizedString
		/**
		 * Enter original text...
		 */
		originalPlaceholder: () => LocalizedString
		/**
		 * Enter modified text...
		 */
		modifiedPlaceholder: () => LocalizedString
		/**
		 * Comparison Mode
		 */
		mode: () => LocalizedString
		/**
		 * Lines
		 */
		lines: () => LocalizedString
		/**
		 * Words
		 */
		words: () => LocalizedString
		/**
		 * Characters
		 */
		characters: () => LocalizedString
		/**
		 * Compare
		 */
		compare: () => LocalizedString
		/**
		 * Swap
		 */
		swap: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Side by Side
		 */
		sideBySide: () => LocalizedString
		/**
		 * Inline
		 */
		inline: () => LocalizedString
		/**
		 * No differences found
		 */
		noDifferences: () => LocalizedString
		/**
		 * Statistics
		 */
		statistics: () => LocalizedString
		/**
		 * Additions
		 */
		additions: () => LocalizedString
		/**
		 * Deletions
		 */
		deletions: () => LocalizedString
		/**
		 * Changes
		 */
		changes: () => LocalizedString
		/**
		 * Result
		 */
		result: () => LocalizedString
		/**
		 * Added
		 */
		added: () => LocalizedString
		/**
		 * Removed
		 */
		removed: () => LocalizedString
		/**
		 * Unchanged
		 */
		unchanged: () => LocalizedString
	}
	yamlJson: {
		/**
		 * YAML ↔ JSON Converter
		 */
		title: () => LocalizedString
		/**
		 * Convert between YAML and JSON formats
		 */
		description: () => LocalizedString
		/**
		 * YAML
		 */
		yaml: () => LocalizedString
		/**
		 * JSON
		 */
		json: () => LocalizedString
		/**
		 * YAML to JSON
		 */
		yamlToJson: () => LocalizedString
		/**
		 * JSON to YAML
		 */
		jsonToYaml: () => LocalizedString
		/**
		 * Enter YAML...
		 */
		yamlPlaceholder: () => LocalizedString
		/**
		 * Enter JSON...
		 */
		jsonPlaceholder: () => LocalizedString
		/**
		 * Convert
		 */
		convert: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Invalid YAML format
		 */
		invalidYaml: () => LocalizedString
		/**
		 * Invalid JSON format
		 */
		invalidJson: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Indent Size
		 */
		indentSize: () => LocalizedString
		/**
		 * Switch Direction
		 */
		'switch': () => LocalizedString
		/**
		 * YAML Input
		 */
		yamlInput: () => LocalizedString
		/**
		 * JSON Input
		 */
		jsonInput: () => LocalizedString
		/**
		 * JSON Output
		 */
		jsonOutput: () => LocalizedString
		/**
		 * YAML Output
		 */
		yamlOutput: () => LocalizedString
		/**
		 * Output will appear here...
		 */
		outputPlaceholder: () => LocalizedString
	}
	sql: {
		/**
		 * SQL Formatter
		 */
		title: () => LocalizedString
		/**
		 * Format and beautify SQL queries
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Output
		 */
		output: () => LocalizedString
		/**
		 * Enter SQL query...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * Formatted SQL will appear here...
		 */
		outputPlaceholder: () => LocalizedString
		/**
		 * Format
		 */
		format: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Uppercase Keywords
		 */
		uppercase: () => LocalizedString
		/**
		 * Indent Size
		 */
		indentSize: () => LocalizedString
		/**
		 * SQL Dialect
		 */
		language: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
	}
	cron: {
		/**
		 * Cron Expression Helper
		 */
		title: () => LocalizedString
		/**
		 * Generate and explain cron expressions
		 */
		description: () => LocalizedString
		/**
		 * Cron Expression
		 */
		expression: () => LocalizedString
		/**
		 * e.g., 0 0 * * *
		 */
		expressionPlaceholder: () => LocalizedString
		/**
		 * Description
		 */
		descriptionLabel: () => LocalizedString
		/**
		 * Next {count} Runs
		 */
		nextRuns: (arg: { count: unknown }) => LocalizedString
		/**
		 * Minute
		 */
		minute: () => LocalizedString
		/**
		 * Hour
		 */
		hour: () => LocalizedString
		/**
		 * Day of Month
		 */
		dayOfMonth: () => LocalizedString
		/**
		 * Month
		 */
		month: () => LocalizedString
		/**
		 * Day of Week
		 */
		dayOfWeek: () => LocalizedString
		/**
		 * Generate
		 */
		generate: () => LocalizedString
		/**
		 * Explain
		 */
		explain: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Invalid cron expression
		 */
		invalidExpression: () => LocalizedString
		/**
		 * Every Minute
		 */
		everyMinute: () => LocalizedString
		/**
		 * Every Hour
		 */
		everyHour: () => LocalizedString
		/**
		 * Every Day
		 */
		everyDay: () => LocalizedString
		/**
		 * Every Week
		 */
		everyWeek: () => LocalizedString
		/**
		 * Every Month
		 */
		everyMonth: () => LocalizedString
		/**
		 * Builder
		 */
		builder: () => LocalizedString
		/**
		 * Help
		 */
		help: () => LocalizedString
		/**
		 * Any value
		 */
		helpAny: () => LocalizedString
		/**
		 * Every N units
		 */
		helpEvery: () => LocalizedString
		/**
		 * Range of values
		 */
		helpRange: () => LocalizedString
		/**
		 * List of values
		 */
		helpList: () => LocalizedString
	}
	qrCode: {
		/**
		 * QR Code Generator
		 */
		title: () => LocalizedString
		/**
		 * Generate QR codes from text or URLs
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Enter text or URL...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * Text
		 */
		text: () => LocalizedString
		/**
		 * Enter text or URL to generate QR code...
		 */
		textPlaceholder: () => LocalizedString
		/**
		 * Size
		 */
		size: () => LocalizedString
		/**
		 * Generate
		 */
		generate: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Copy Link
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Error Correction
		 */
		errorCorrection: () => LocalizedString
		/**
		 * Low
		 */
		low: () => LocalizedString
		/**
		 * Medium
		 */
		medium: () => LocalizedString
		/**
		 * Quartile
		 */
		quartile: () => LocalizedString
		/**
		 * High
		 */
		high: () => LocalizedString
		/**
		 * Low (~7%)
		 */
		errorLevelL: () => LocalizedString
		/**
		 * Medium (~15%)
		 */
		errorLevelM: () => LocalizedString
		/**
		 * Quartile (~25%)
		 */
		errorLevelQ: () => LocalizedString
		/**
		 * High (~30%)
		 */
		errorLevelH: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Preview
		 */
		preview: () => LocalizedString
		/**
		 * Enter text to generate QR code
		 */
		noQRCode: () => LocalizedString
		/**
		 * QR code downloaded
		 */
		downloadSuccess: () => LocalizedString
	}
}

export type Formatters = {}
