// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * J​S​O​N​ ​E​d​i​t​o​r
		 */
		jsonEditor: string
		/**
		 * E​n​c​o​d​e​/​D​e​c​o​d​e
		 */
		encodeDecode: string
		/**
		 * H​a​s​h​ ​G​e​n​e​r​a​t​o​r
		 */
		hash: string
		/**
		 * T​i​m​e​s​t​a​m​p​ ​C​o​n​v​e​r​t​e​r
		 */
		timestamp: string
	}
	header: {
		/**
		 * J​S​O​N​ ​E​d​i​t​o​r
		 */
		title: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copyError: string
		/**
		 * F​o​r​m​a​t
		 */
		format: string
		/**
		 * M​i​n​i​f​y
		 */
		minify: string
		/**
		 * S​a​m​p​l​e​ ​D​a​t​a
		 */
		sample: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
	}
	editor: {
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​J​S​O​N​ ​d​a​t​a​ ​h​e​r​e​.​.​.
		 */
		placeholder: string
		/**
		 * I​n​v​a​l​i​d​ ​J​S​O​N
		 */
		invalidJson: string
		/**
		 * V​a​l​i​d​ ​J​S​O​N
		 */
		validJson: string
		/**
		 * E​n​t​e​r​ ​U​R​L​ ​t​o​ ​f​e​t​c​h​ ​J​S​O​N​.​.​.
		 */
		urlPlaceholder: string
		/**
		 * U​R​L​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		urlRequired: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​d​a​t​a
		 */
		fetchError: string
		/**
		 * G​o
		 */
		go: string
		/**
		 * R​e​q​u​e​s​t​ ​S​e​t​t​i​n​g​s
		 */
		requestSettings: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​H​T​T​P​ ​h​e​a​d​e​r​s​ ​a​n​d​ ​r​e​q​u​e​s​t​ ​b​o​d​y
		 */
		requestSettingsDescription: string
		/**
		 * H​e​a​d​e​r​s
		 */
		headers: string
		/**
		 * H​e​a​d​e​r​ ​k​e​y
		 */
		headerKey: string
		/**
		 * H​e​a​d​e​r​ ​v​a​l​u​e
		 */
		headerValue: string
		/**
		 * A​d​d​ ​H​e​a​d​e​r
		 */
		addHeader: string
		/**
		 * B​o​d​y
		 */
		body: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​b​o​d​y​ ​f​o​r​ ​P​O​S​T​/​P​U​T​/​P​A​T​C​H​ ​r​e​q​u​e​s​t​s​.
		 */
		bodyDescription: string
		/**
		 * E​n​t​e​r​ ​r​e​q​u​e​s​t​ ​b​o​d​y​ ​(​J​S​O​N​,​ ​X​M​L​,​ ​e​t​c​.​)
		 */
		bodyPlaceholder: string
		/**
		 * U​s​e​ ​e​d​i​t​o​r​ ​c​o​n​t​e​n​t​ ​a​s​ ​r​e​q​u​e​s​t​ ​b​o​d​y
		 */
		useEditorContent: string
		/**
		 * S​e​n​d​ ​a​s​ ​r​a​w​ ​t​e​x​t​ ​(​d​o​n​'​t​ ​p​a​r​s​e​ ​a​s​ ​J​S​O​N​)
		 */
		sendAsRawText: string
		/**
		 * C​l​e​a​r​ ​A​l​l
		 */
		clearAll: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​l​e​a​r​ ​a​l​l​ ​s​e​t​t​i​n​g​s​?​ ​T​h​i​s​ ​w​i​l​l​ ​r​e​m​o​v​e​ ​a​l​l​ ​s​a​v​e​d​ ​h​e​a​d​e​r​s​,​ ​b​o​d​y​,​ ​a​n​d​ ​U​R​L​ ​f​r​o​m​ ​s​t​o​r​a​g​e​.
		 */
		clearAllConfirm: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * R​e​g​e​n​e​r​a​t​e
		 */
		regenerate: string
		/**
		 * R​e​g​e​n​e​r​a​t​e​ ​v​a​l​u​e​s​ ​w​h​i​l​e​ ​p​r​e​s​e​r​v​i​n​g​ ​J​S​O​N​ ​s​t​r​u​c​t​u​r​e
		 */
		regenerateTooltip: string
		/**
		 * J​S​O​N​ ​v​a​l​u​e​s​ ​r​e​g​e​n​e​r​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		regenerateSuccess: string
	}
	graph: {
		/**
		 * S​h​o​w​ ​{​c​o​u​n​t​}​ ​m​o​r​e
		 * @param {unknown} count
		 */
		showMore: RequiredParams<'count'>
		/**
		 * S​h​o​w​ ​l​e​s​s
		 */
		showLess: string
		/**
		 * E​x​p​a​n​d
		 */
		expand: string
		/**
		 * C​o​l​l​a​p​s​e
		 */
		collapse: string
		/**
		 * E​x​p​a​n​d​ ​a​l​l
		 */
		expandAll: string
	}
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * 한​국​어
		 */
		ko: string
		/**
		 * 日​本​語
		 */
		ja: string
	}
	footer: {
		/**
		 * R​e​a​d​y
		 */
		ready: string
	}
	tabs: {
		/**
		 * R​e​n​a​m​e
		 */
		rename: string
		/**
		 * D​u​p​l​i​c​a​t​e
		 */
		duplicate: string
		/**
		 * E​x​p​o​r​t​ ​J​S​O​N
		 */
		exportJson: string
		/**
		 * C​l​o​s​e​ ​T​a​b
		 */
		closeTab: string
		/**
		 * I​m​p​o​r​t​ ​J​S​O​N​ ​F​i​l​e
		 */
		importJsonFile: string
		/**
		 * N​e​w​ ​T​a​b
		 */
		newTab: string
		/**
		 * I​m​p​o​r​t
		 */
		'import': string
	}
	encodeDecode: {
		/**
		 * E​n​c​o​d​e​/​D​e​c​o​d​e
		 */
		title: string
		/**
		 * E​n​c​o​d​e​ ​o​r​ ​d​e​c​o​d​e​ ​t​e​x​t​ ​u​s​i​n​g​ ​v​a​r​i​o​u​s​ ​e​n​c​o​d​i​n​g​ ​m​e​t​h​o​d​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * O​u​t​p​u​t
		 */
		output: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​e​n​c​o​d​e​ ​o​r​ ​d​e​c​o​d​e​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * B​a​s​e​6​4
		 */
		base64: string
		/**
		 * B​a​s​e​6​4​ ​E​n​c​o​d​e
		 */
		base64Encode: string
		/**
		 * B​a​s​e​6​4​ ​D​e​c​o​d​e
		 */
		base64Decode: string
		/**
		 * U​R​L
		 */
		url: string
		/**
		 * U​R​L​ ​E​n​c​o​d​e
		 */
		urlEncode: string
		/**
		 * U​R​L​ ​D​e​c​o​d​e
		 */
		urlDecode: string
		/**
		 * E​n​c​o​d​e
		 */
		encode: string
		/**
		 * D​e​c​o​d​e
		 */
		decode: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​d​e​c​o​d​e​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​p​u​t​.
		 */
		decodeError: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​e​n​c​o​d​e​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​p​u​t​.
		 */
		encodeError: string
	}
	hash: {
		/**
		 * H​a​s​h​ ​G​e​n​e​r​a​t​o​r
		 */
		title: string
		/**
		 * G​e​n​e​r​a​t​e​ ​h​a​s​h​ ​v​a​l​u​e​s​ ​u​s​i​n​g​ ​v​a​r​i​o​u​s​ ​a​l​g​o​r​i​t​h​m​s
		 */
		description: string
		/**
		 * I​n​p​u​t
		 */
		input: string
		/**
		 * E​n​t​e​r​ ​t​e​x​t​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​h​a​s​h​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * M​D​5
		 */
		md5: string
		/**
		 * S​H​A​-​1
		 */
		sha1: string
		/**
		 * S​H​A​-​2​5​6
		 */
		sha256: string
		/**
		 * S​H​A​-​5​1​2
		 */
		sha512: string
		/**
		 * G​e​n​e​r​a​t​e
		 */
		generate: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * R​e​s​u​l​t
		 */
		result: string
		/**
		 * A​l​g​o​r​i​t​h​m
		 */
		algorithm: string
	}
	timestamp: {
		/**
		 * T​i​m​e​s​t​a​m​p​ ​C​o​n​v​e​r​t​e​r
		 */
		title: string
		/**
		 * C​o​n​v​e​r​t​ ​b​e​t​w​e​e​n​ ​t​i​m​e​s​t​a​m​p​ ​a​n​d​ ​d​a​t​e
		 */
		description: string
		/**
		 * T​i​m​e​s​t​a​m​p​ ​t​o​ ​D​a​t​e
		 */
		timestampToDate: string
		/**
		 * D​a​t​e​ ​t​o​ ​T​i​m​e​s​t​a​m​p
		 */
		dateToTimestamp: string
		/**
		 * T​i​m​e​s​t​a​m​p
		 */
		timestamp: string
		/**
		 * E​n​t​e​r​ ​t​i​m​e​s​t​a​m​p​ ​(​e​.​g​.​,​ ​1​2​3​4​5​6​7​8​9​0​)
		 */
		timestampPlaceholder: string
		/**
		 * D​a​t​e
		 */
		date: string
		/**
		 * C​u​r​r​e​n​t​ ​T​i​m​e​s​t​a​m​p
		 */
		currentTimestamp: string
		/**
		 * C​o​n​v​e​r​t
		 */
		convert: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copySuccess: string
		/**
		 * I​n​v​a​l​i​d​ ​t​i​m​e​s​t​a​m​p
		 */
		invalidTimestamp: string
		/**
		 * I​n​v​a​l​i​d​ ​d​a​t​e
		 */
		invalidDate: string
		/**
		 * M​i​l​l​i​s​e​c​o​n​d​s
		 */
		milliseconds: string
		/**
		 * S​e​c​o​n​d​s
		 */
		seconds: string
		/**
		 * U​n​i​t
		 */
		unit: string
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * JSON Editor
		 */
		jsonEditor: () => LocalizedString
		/**
		 * Encode/Decode
		 */
		encodeDecode: () => LocalizedString
		/**
		 * Hash Generator
		 */
		hash: () => LocalizedString
		/**
		 * Timestamp Converter
		 */
		timestamp: () => LocalizedString
	}
	header: {
		/**
		 * JSON Editor
		 */
		title: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Failed to copy to clipboard
		 */
		copyError: () => LocalizedString
		/**
		 * Format
		 */
		format: () => LocalizedString
		/**
		 * Minify
		 */
		minify: () => LocalizedString
		/**
		 * Sample Data
		 */
		sample: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
	}
	editor: {
		/**
		 * Enter your JSON data here...
		 */
		placeholder: () => LocalizedString
		/**
		 * Invalid JSON
		 */
		invalidJson: () => LocalizedString
		/**
		 * Valid JSON
		 */
		validJson: () => LocalizedString
		/**
		 * Enter URL to fetch JSON...
		 */
		urlPlaceholder: () => LocalizedString
		/**
		 * URL is required
		 */
		urlRequired: () => LocalizedString
		/**
		 * Failed to fetch data
		 */
		fetchError: () => LocalizedString
		/**
		 * Go
		 */
		go: () => LocalizedString
		/**
		 * Request Settings
		 */
		requestSettings: () => LocalizedString
		/**
		 * Configure HTTP headers and request body
		 */
		requestSettingsDescription: () => LocalizedString
		/**
		 * Headers
		 */
		headers: () => LocalizedString
		/**
		 * Header key
		 */
		headerKey: () => LocalizedString
		/**
		 * Header value
		 */
		headerValue: () => LocalizedString
		/**
		 * Add Header
		 */
		addHeader: () => LocalizedString
		/**
		 * Body
		 */
		body: () => LocalizedString
		/**
		 * Configure the request body for POST/PUT/PATCH requests.
		 */
		bodyDescription: () => LocalizedString
		/**
		 * Enter request body (JSON, XML, etc.)
		 */
		bodyPlaceholder: () => LocalizedString
		/**
		 * Use editor content as request body
		 */
		useEditorContent: () => LocalizedString
		/**
		 * Send as raw text (don't parse as JSON)
		 */
		sendAsRawText: () => LocalizedString
		/**
		 * Clear All
		 */
		clearAll: () => LocalizedString
		/**
		 * Are you sure you want to clear all settings? This will remove all saved headers, body, and URL from storage.
		 */
		clearAllConfirm: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Regenerate
		 */
		regenerate: () => LocalizedString
		/**
		 * Regenerate values while preserving JSON structure
		 */
		regenerateTooltip: () => LocalizedString
		/**
		 * JSON values regenerated successfully
		 */
		regenerateSuccess: () => LocalizedString
	}
	graph: {
		/**
		 * Show {count} more
		 */
		showMore: (arg: { count: unknown }) => LocalizedString
		/**
		 * Show less
		 */
		showLess: () => LocalizedString
		/**
		 * Expand
		 */
		expand: () => LocalizedString
		/**
		 * Collapse
		 */
		collapse: () => LocalizedString
		/**
		 * Expand all
		 */
		expandAll: () => LocalizedString
	}
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * 한국어
		 */
		ko: () => LocalizedString
		/**
		 * 日本語
		 */
		ja: () => LocalizedString
	}
	footer: {
		/**
		 * Ready
		 */
		ready: () => LocalizedString
	}
	tabs: {
		/**
		 * Rename
		 */
		rename: () => LocalizedString
		/**
		 * Duplicate
		 */
		duplicate: () => LocalizedString
		/**
		 * Export JSON
		 */
		exportJson: () => LocalizedString
		/**
		 * Close Tab
		 */
		closeTab: () => LocalizedString
		/**
		 * Import JSON File
		 */
		importJsonFile: () => LocalizedString
		/**
		 * New Tab
		 */
		newTab: () => LocalizedString
		/**
		 * Import
		 */
		'import': () => LocalizedString
	}
	encodeDecode: {
		/**
		 * Encode/Decode
		 */
		title: () => LocalizedString
		/**
		 * Encode or decode text using various encoding methods
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Output
		 */
		output: () => LocalizedString
		/**
		 * Enter text to encode or decode...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * Base64
		 */
		base64: () => LocalizedString
		/**
		 * Base64 Encode
		 */
		base64Encode: () => LocalizedString
		/**
		 * Base64 Decode
		 */
		base64Decode: () => LocalizedString
		/**
		 * URL
		 */
		url: () => LocalizedString
		/**
		 * URL Encode
		 */
		urlEncode: () => LocalizedString
		/**
		 * URL Decode
		 */
		urlDecode: () => LocalizedString
		/**
		 * Encode
		 */
		encode: () => LocalizedString
		/**
		 * Decode
		 */
		decode: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Failed to decode. Please check your input.
		 */
		decodeError: () => LocalizedString
		/**
		 * Failed to encode. Please check your input.
		 */
		encodeError: () => LocalizedString
	}
	hash: {
		/**
		 * Hash Generator
		 */
		title: () => LocalizedString
		/**
		 * Generate hash values using various algorithms
		 */
		description: () => LocalizedString
		/**
		 * Input
		 */
		input: () => LocalizedString
		/**
		 * Enter text to generate hash...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * MD5
		 */
		md5: () => LocalizedString
		/**
		 * SHA-1
		 */
		sha1: () => LocalizedString
		/**
		 * SHA-256
		 */
		sha256: () => LocalizedString
		/**
		 * SHA-512
		 */
		sha512: () => LocalizedString
		/**
		 * Generate
		 */
		generate: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Result
		 */
		result: () => LocalizedString
		/**
		 * Algorithm
		 */
		algorithm: () => LocalizedString
	}
	timestamp: {
		/**
		 * Timestamp Converter
		 */
		title: () => LocalizedString
		/**
		 * Convert between timestamp and date
		 */
		description: () => LocalizedString
		/**
		 * Timestamp to Date
		 */
		timestampToDate: () => LocalizedString
		/**
		 * Date to Timestamp
		 */
		dateToTimestamp: () => LocalizedString
		/**
		 * Timestamp
		 */
		timestamp: () => LocalizedString
		/**
		 * Enter timestamp (e.g., 1234567890)
		 */
		timestampPlaceholder: () => LocalizedString
		/**
		 * Date
		 */
		date: () => LocalizedString
		/**
		 * Current Timestamp
		 */
		currentTimestamp: () => LocalizedString
		/**
		 * Convert
		 */
		convert: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copySuccess: () => LocalizedString
		/**
		 * Invalid timestamp
		 */
		invalidTimestamp: () => LocalizedString
		/**
		 * Invalid date
		 */
		invalidDate: () => LocalizedString
		/**
		 * Milliseconds
		 */
		milliseconds: () => LocalizedString
		/**
		 * Seconds
		 */
		seconds: () => LocalizedString
		/**
		 * Unit
		 */
		unit: () => LocalizedString
	}
}

export type Formatters = {}
